---
#
# Ansible managed
#
repository:
  description: Install subversion and create repositories on your system.
  homepage: https://buluma.github.io/
  topics: subversion, ansible, molecule, tox, playbook
